server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 100000000
      maxRequestSize: 200000000
  neo4j:
#      url: bolt://192.168.200.60:7687  #3.x
      url: neo4j://192.168.200.60:7687 #4.x
      username: neo4j
      password: ILoveBaiyuetong@12
  datasource:
      url: jdbc:mysql://192.168.200.60:13307/kg?useSSL=false&serverTimezone=UTC
      driverClassName: com.mysql.cj.jdbc.Driver
      username: pmy_baiyuetong
      password: fd3a41ab-3161-9500-1b6f-a3f4551cc830
      type: com.zaxxer.hikari.HikariDataSource
mybatis:
  typeAliasesPackage: com.warmer.kgmaker.entity
  mapperLocations: classpath*:/mapping/*.xml
file:
  serverurl:  http://192.168.200.38:8080/
  location : /Users/junwei/data/csv   #如果是Windows情况下，格式是 D:\\kgmanager\\csv\\   linx 格式"/home/kgmanager/csv/";